id: editor
permissions:
  - 'customize shortcut links'
  - 'access toolbar'
  - 'access admin audit trail'
  - 'access coffee'
  - 'access responsive preview'
  - 'clone node entity'
  - 'access taxonomy manager list'
