__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_blog
core.entity_form_display.node.varbase_blog.default:
  expected_config:
    content:
      title:
        third_party_settings: {}
  update_actions:
    change:
      content:
        title:
          third_party_settings:
            advanced_text_formatter:
              show_token_tree: 0
            length_indicator:
              indicator: true
              indicator_opt:
                optimax: 50
                optimin: 15
                tolerance: 10
            maxlength:
              maxlength_js: null
              maxlength_js_label: "Content limited to @limit characters, remaining: <strong>@remaining</strong>"
