__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_security
__global_actions:
  expected_config: {}
  update_actions: {}
  install_modules:
    - flood_control
